name: Deploy to dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        
    - name: Upload and deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "dist/*"
        target: "/tmp/deploy/"
        strip_components: 0
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Create new release directory with timestamp
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          RELEASE_DIR="/var/www/edify.budd.systems/releases/$TIMESTAMP"
          mkdir -p $RELEASE_DIR
          
          # Move files from temp to release directory
          mv /tmp/deploy/* $RELEASE_DIR/
          
          # Clean up temp directory
          rm -rf /tmp/deploy
        
    - name: Update symlinks and restart
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Get latest release
          LATEST_RELEASE=$(ls -t /var/www/edify.budd.systems/releases/ | head -n1)
          
          # Update symlink
          ln -sfn /var/www/edify.budd.systems/releases/$LATEST_RELEASE /var/www/edify.budd.systems/current
          
          # Set proper permissions
          chown -R www-data:www-data /var/www/edify.budd.systems/current/
          chmod -R 755 /var/www/edify.budd.systems/current/
          
          # Restart Nginx
          systemctl reload nginx
          
          # Health check
          curl -f https://edify.budd.systems || exit 1
