name: Deploy to dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        
    - name: Add cache busting
      run: |
        # Add timestamp to index.html to prevent caching
        TIMESTAMP=$(date +%s)
        sed -i "s|<title>|<title><!-- Deployed: $TIMESTAMP -->|" dist/index.html
        echo "Added deployment timestamp: $TIMESTAMP"
        
    # New: hard-clean target before uploading to avoid stale files
    - name: Cleanup target directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p /var/www/edify.budd.systems/current
          rm -rf /var/www/edify.budd.systems/current/*
        
    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/edify.budd.systems/current/"
        strip_components: 0
        overwrite: true
        
    - name: Set permissions and restart
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Set proper permissions
          chown -R www-data:www-data /var/www/edify.budd.systems/current/
          chmod -R 755 /var/www/edify.budd.systems/current/
          
          # Restart Nginx
          systemctl reload nginx
          
          # Health check
          curl -f "https://edify.budd.systems" || exit 1
          
          echo "Deployment completed successfully!"
